// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyCuaHangSach.Models;

namespace QuanLyCuaHangSach.Migrations
{
    [DbContext(typeof(QLCHSContext))]
    partial class QLCHSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Chitietnhap", b =>
                {
                    b.Property<int>("Idctn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCTN")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float?>("Dongianhap")
                        .HasColumnType("real")
                        .HasColumnName("DONGIANHAP");

                    b.Property<string>("Dvt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DVT");

                    b.Property<int?>("Phieudathangmuaidpdhm")
                        .HasColumnType("int")
                        .HasColumnName("PHIEUDATHANGMUAIDPDHM");

                    b.Property<int?>("Sachidsach")
                        .HasColumnType("int")
                        .HasColumnName("SACHIDSACH");

                    b.Property<int?>("Sldat")
                        .HasColumnType("int")
                        .HasColumnName("SLDAT");

                    b.Property<int?>("Slgiao")
                        .HasColumnType("int")
                        .HasColumnName("SLGIAO");

                    b.Property<bool?>("Xacnhan")
                        .HasColumnType("bit")
                        .HasColumnName("XACNHAN");

                    b.HasKey("Idctn")
                        .HasName("PK__CHITIETN__91A8964E485AA43C");

                    b.HasIndex("Phieudathangmuaidpdhm");

                    b.HasIndex("Sachidsach");

                    b.ToTable("CHITIETNHAP");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Chitietxuat", b =>
                {
                    b.Property<int>("Idctx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCTX")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float?>("Dongiaban")
                        .HasColumnType("real")
                        .HasColumnName("DONGIABAN");

                    b.Property<string>("Dvt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DVT");

                    b.Property<int?>("PhieudathangbanIdpdhb")
                        .HasColumnType("int");

                    b.Property<int?>("Phieudathangbanidpdhb")
                        .HasColumnType("int")
                        .HasColumnName("PHIEUDATHANGBANIDPDHB");

                    b.Property<int?>("Sachidsach")
                        .HasColumnType("int")
                        .HasColumnName("SACHIDSACH");

                    b.Property<int?>("Sldat")
                        .HasColumnType("int")
                        .HasColumnName("SLDAT");

                    b.Property<int?>("Slgiao")
                        .HasColumnType("int")
                        .HasColumnName("SLGIAO");

                    b.Property<bool?>("Xacnhan")
                        .HasColumnType("bit")
                        .HasColumnName("XACNHAN");

                    b.HasKey("Idctx")
                        .HasName("PK__CHITIETX__91A897B077062A08");

                    b.HasIndex("Phieudathangbanidpdhb");

                    b.HasIndex("Sachidsach");

                    b.ToTable("CHITIETXUAT");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Donvivanchuyen", b =>
                {
                    b.Property<int>("Iddvvc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDVVC")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Diachi")
                        .HasColumnType("ntext")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Ghichu")
                        .HasColumnType("ntext")
                        .HasColumnName("GHICHU");

                    b.Property<string>("Madvvc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MADVVC");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Sdt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tendvvc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENDVVC");

                    b.HasKey("Iddvvc")
                        .HasName("PK__DONVIVAN__303C0973B65D02FC");

                    b.ToTable("DONVIVANCHUYEN");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Httt", b =>
                {
                    b.Property<int>("Idhttt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDHTTT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Ghichu")
                        .HasColumnType("ntext")
                        .HasColumnName("GHICHU");

                    b.Property<string>("Mahttt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MAHTTT");

                    b.Property<int?>("Nganhangidnganhang")
                        .HasColumnType("int")
                        .HasColumnName("NGANHANGIDNGANHANG");

                    b.Property<string>("Tenhttt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENHTTT");

                    b.HasKey("Idhttt")
                        .HasName("PK__HTTT__9DCEA6E366B6E543");

                    b.HasIndex("Nganhangidnganhang");

                    b.ToTable("HTTT");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Khachhang", b =>
                {
                    b.Property<int>("Idkhachhang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDKHACHHANG")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Diachi")
                        .HasColumnType("ntext")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMAGE");

                    b.Property<string>("Makhachhang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MAKHACHHANG");

                    b.Property<int?>("Nganhangidnganhang")
                        .HasColumnType("int")
                        .HasColumnName("NGANHANGIDNGANHANG");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ROLE");

                    b.Property<string>("Sdt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDT");

                    b.Property<string>("Stk")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STK");

                    b.Property<string>("Tenkhachhang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENKHACHHANG");

                    b.HasKey("Idkhachhang")
                        .HasName("PK__KHACHHAN__629294BE3ECB49F8");

                    b.HasIndex("Nganhangidnganhang");

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Loaisach", b =>
                {
                    b.Property<int>("Idloai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDLOAI")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Maloai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MALOAI");

                    b.Property<string>("Tenloai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENLOAI");

                    b.HasKey("Idloai")
                        .HasName("PK__LOAISACH__0CDEF51920006DAA");

                    b.ToTable("LOAISACH");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Nganhang", b =>
                {
                    b.Property<int>("Idnganhang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNGANHANG")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Ghichu")
                        .HasColumnType("ntext")
                        .HasColumnName("GHICHU");

                    b.Property<string>("Manganhang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MANGANHANG");

                    b.Property<string>("Tennganhang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENNGANHANG");

                    b.HasKey("Idnganhang")
                        .HasName("PK__NGANHANG__4C4BF656F11415DB");

                    b.ToTable("NGANHANG");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Ngonngu", b =>
                {
                    b.Property<int>("Idngonngu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNGONNGU")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Tenngongu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENNGONGU");

                    b.HasKey("Idngonngu")
                        .HasName("PK__NGONNGU__F2344A3F6F02F454");

                    b.ToTable("NGONNGU");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Nhacungcap", b =>
                {
                    b.Property<int>("Idncc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNCC")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Diachi")
                        .HasColumnType("ntext")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Ghichu")
                        .HasColumnType("ntext")
                        .HasColumnName("GHICHU");

                    b.Property<string>("Mancc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MANCC");

                    b.Property<string>("Masothue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MASOTHUE");

                    b.Property<int?>("Nganhangidnganhang")
                        .HasColumnType("int")
                        .HasColumnName("NGANHANGIDNGANHANG");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Sdt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDT");

                    b.Property<string>("Stk")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("STK");

                    b.Property<string>("Tenncc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENNCC");

                    b.HasKey("Idncc")
                        .HasName("PK__NHACUNGC__945E4705B47300B6");

                    b.HasIndex("Nganhangidnganhang");

                    b.ToTable("NHACUNGCAP");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Nhanvien", b =>
                {
                    b.Property<int>("Idnhanvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNHANVIEN")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("IMAGE");

                    b.Property<string>("Manhanvien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MANHANVIEN");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ROLE");

                    b.Property<string>("Sdt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tennhanvien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENNHANVIEN");

                    b.HasKey("Idnhanvien")
                        .HasName("PK__NHANVIEN__CEEFA9833F1023A1");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Nhaxuatban", b =>
                {
                    b.Property<int>("Idnxb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNXB")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Manxb")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MANXB");

                    b.Property<string>("Tennxb")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENNXB");

                    b.HasKey("Idnxb")
                        .HasName("PK__NHAXUATB__945B98FB7353941D");

                    b.ToTable("NHAXUATBAN");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Noidungthanhtoan", b =>
                {
                    b.Property<int>("Idndtt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNDTT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Phieudathangmuaidpdhm")
                        .HasColumnType("int")
                        .HasColumnName("PHIEUDATHANGMUAIDPDHM");

                    b.Property<int?>("Phieuthanhtoantienmuaidptttm")
                        .HasColumnType("int")
                        .HasColumnName("PHIEUTHANHTOANTIENMUAIDPTTTM");

                    b.Property<double?>("Sotienthanhtoan")
                        .HasColumnType("float")
                        .HasColumnName("SOTIENTHANHTOAN");

                    b.HasKey("Idndtt")
                        .HasName("PK__NOIDUNGT__383E185187B9A3BC");

                    b.HasIndex("Phieudathangmuaidpdhm");

                    b.HasIndex("Phieuthanhtoantienmuaidptttm");

                    b.ToTable("NOIDUNGTHANHTOAN");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Noidungthutien", b =>
                {
                    b.Property<int>("Idndthu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNDTHU")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Phieudathangbanidpdhb")
                        .HasColumnType("int")
                        .HasColumnName("PHIEUDATHANGBANIDPDHB");

                    b.Property<int?>("Phieuthutienbanidpttb")
                        .HasColumnType("int")
                        .HasColumnName("PHIEUTHUTIENBANIDPTTB");

                    b.Property<double?>("Sotienthu")
                        .HasColumnType("float")
                        .HasColumnName("SOTIENTHU");

                    b.HasKey("Idndthu")
                        .HasName("PK__NOIDUNGT__3EAAF7A5D490F293");

                    b.HasIndex("Phieudathangbanidpdhb");

                    b.HasIndex("Phieuthutienbanidpttb");

                    b.ToTable("NOIDUNGTHUTIEN");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Phieudathangban", b =>
                {
                    b.Property<int>("Idpdhb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPDHB")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int?>("Donvivanchuyeniddvvc")
                        .HasColumnType("int")
                        .HasColumnName("DONVIVANCHUYENIDDVVC");

                    b.Property<string>("Ghichu")
                        .HasColumnType("ntext")
                        .HasColumnName("GHICHU");

                    b.Property<int?>("Khachhangidkhachhang")
                        .HasColumnType("int")
                        .HasColumnName("KHACHHANGIDKHACHHANG");

                    b.Property<DateTime?>("Ngaydat")
                        .HasColumnType("date")
                        .HasColumnName("NGAYDAT");

                    b.Property<DateTime?>("Ngaygiaohang")
                        .HasColumnType("date")
                        .HasColumnName("NGAYGIAOHANG");

                    b.Property<DateTime?>("Ngaytiepnhan")
                        .HasColumnType("date")
                        .HasColumnName("NGAYTIEPNHAN");

                    b.Property<int?>("Nhanvienidnhanvien")
                        .HasColumnType("int")
                        .HasColumnName("NHANVIENIDNHANVIEN");

                    b.Property<string>("Sopdhb")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SOPDHB");

                    b.Property<int?>("Trangthaiidtt")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAIIDTT");

                    b.HasKey("Idpdhb")
                        .HasName("PK__PHIEUDAT__A2D2C985025BBECC");

                    b.HasIndex("Donvivanchuyeniddvvc");

                    b.HasIndex("Khachhangidkhachhang");

                    b.HasIndex("Nhanvienidnhanvien");

                    b.HasIndex("Trangthaiidtt");

                    b.ToTable("PHIEUDATHANGBAN");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Phieudathangmua", b =>
                {
                    b.Property<int>("Idpdhm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPDHM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int?>("Donvivanchuyeniddvvc")
                        .HasColumnType("int")
                        .HasColumnName("DONVIVANCHUYENIDDVVC");

                    b.Property<string>("Ghichu")
                        .HasColumnType("ntext")
                        .HasColumnName("GHICHU");

                    b.Property<DateTime?>("Ngaydat")
                        .HasColumnType("date")
                        .HasColumnName("NGAYDAT");

                    b.Property<DateTime?>("Ngaygiaohang")
                        .HasColumnType("date")
                        .HasColumnName("NGAYGIAOHANG");

                    b.Property<DateTime?>("Ngaytiepnhan")
                        .HasColumnType("date")
                        .HasColumnName("NGAYTIEPNHAN");

                    b.Property<int?>("Nhacungcapidncc")
                        .HasColumnType("int")
                        .HasColumnName("NHACUNGCAPIDNCC");

                    b.Property<int?>("Nhanvienidnhanvien")
                        .HasColumnType("int")
                        .HasColumnName("NHANVIENIDNHANVIEN");

                    b.Property<string>("Sopdhm")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SOPDHM");

                    b.Property<int?>("Trangthaiidtt")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAIIDTT");

                    b.HasKey("Idpdhm")
                        .HasName("PK__PHIEUDAT__A2D2C988BD813EC2");

                    b.HasIndex("Donvivanchuyeniddvvc");

                    b.HasIndex("Nhacungcapidncc");

                    b.HasIndex("Nhanvienidnhanvien");

                    b.HasIndex("Trangthaiidtt");

                    b.ToTable("PHIEUDATHANGMUA");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Phieuthanhtoantienmua", b =>
                {
                    b.Property<int>("Idptttm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPTTTM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int?>("Htttidhttt")
                        .HasColumnType("int")
                        .HasColumnName("HTTTIDHTTT");

                    b.Property<DateTime?>("Ngaythanhtoan")
                        .HasColumnType("date")
                        .HasColumnName("NGAYTHANHTOAN");

                    b.Property<int?>("Nhanvienidnhanvien")
                        .HasColumnType("int")
                        .HasColumnName("NHANVIENIDNHANVIEN");

                    b.Property<string>("Soptttm")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SOPTTTM");

                    b.HasKey("Idptttm")
                        .HasName("PK__PHIEUTHA__0228700E6276F61A");

                    b.HasIndex("Htttidhttt");

                    b.HasIndex("Nhanvienidnhanvien");

                    b.ToTable("PHIEUTHANHTOANTIENMUA");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Phieuthutienban", b =>
                {
                    b.Property<int>("Idpttb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPTTB")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int?>("Htttidhttt")
                        .HasColumnType("int")
                        .HasColumnName("HTTTIDHTTT");

                    b.Property<int?>("Ngaythutien")
                        .HasColumnType("int")
                        .HasColumnName("NGAYTHUTIEN");

                    b.Property<int?>("Nhanvienidnhanvien")
                        .HasColumnType("int")
                        .HasColumnName("NHANVIENIDNHANVIEN");

                    b.Property<string>("Sopttb")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SOPTTB");

                    b.HasKey("Idpttb")
                        .HasName("PK__PHIEUTHU__8F8EFC5B7435F6F1");

                    b.HasIndex("Htttidhttt");

                    b.HasIndex("Nhanvienidnhanvien");

                    b.ToTable("PHIEUTHUTIENBAN");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Sach", b =>
                {
                    b.Property<int>("Idsach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDSACH")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Ghichu")
                        .HasColumnType("ntext")
                        .HasColumnName("GHICHU");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMAGE");

                    b.Property<string>("Lanxb")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LANXB");

                    b.Property<int?>("Loaisachidloai")
                        .HasColumnType("int")
                        .HasColumnName("LOAISACHIDLOAI");

                    b.Property<string>("Masach")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MASACH");

                    b.Property<DateTime?>("Ngayxb")
                        .HasColumnType("date")
                        .HasColumnName("NGAYXB");

                    b.Property<int?>("Ngonnguidngonngu")
                        .HasColumnType("int")
                        .HasColumnName("NGONNGUIDNGONNGU");

                    b.Property<int?>("Nhaxuatbanidnxb")
                        .HasColumnType("int")
                        .HasColumnName("NHAXUATBANIDNXB");

                    b.Property<int?>("Tacgiaidtacgia")
                        .HasColumnType("int")
                        .HasColumnName("TACGIAIDTACGIA");

                    b.Property<string>("Tensach")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENSACH");

                    b.HasKey("Idsach")
                        .HasName("PK__SACH__8FB3F1150C47B9C7");

                    b.HasIndex("Loaisachidloai");

                    b.HasIndex("Ngonnguidngonngu");

                    b.HasIndex("Nhaxuatbanidnxb");

                    b.HasIndex("Tacgiaidtacgia");

                    b.ToTable("SACH");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Tacgia", b =>
                {
                    b.Property<int>("Idtacgia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTACGIA")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Ghichu")
                        .HasColumnType("ntext")
                        .HasColumnName("GHICHU");

                    b.Property<string>("Matacgia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MATACGIA");

                    b.Property<string>("Tentacgia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENTACGIA");

                    b.HasKey("Idtacgia")
                        .HasName("PK__TACGIA__9D7CC9B0637EF363");

                    b.ToTable("TACGIA");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Trangthai", b =>
                {
                    b.Property<int>("Idtt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Tentt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENTT");

                    b.HasKey("Idtt")
                        .HasName("PK__TRANGTHA__B87C3AF87454C78A");

                    b.ToTable("TRANGTHAI");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Chitietnhap", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Phieudathangmua", "PhieudathangmuaidpdhmNavigation")
                        .WithMany("Chitietnhaps")
                        .HasForeignKey("Phieudathangmuaidpdhm")
                        .HasConstraintName("FKCHITIETNHA597063");

                    b.HasOne("QuanLyCuaHangSach.Models.Sach", "SachidsachNavigation")
                        .WithMany("Chitietnhaps")
                        .HasForeignKey("Sachidsach")
                        .HasConstraintName("FKCHITIETNHA209084");

                    b.Navigation("PhieudathangmuaidpdhmNavigation");

                    b.Navigation("SachidsachNavigation");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Chitietxuat", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Phieudathangban", "Phieudathangban")
                        .WithMany("Chitietxuatss")
                        .HasForeignKey("PhieudathangbanIdpdhb");

                    b.HasOne("QuanLyCuaHangSach.Models.Phieudathangban", "PhieudathangbanidpdhbNavigation")
                        .WithMany("Chitietxuats")
                        .HasForeignKey("Phieudathangbanidpdhb")
                        .HasConstraintName("FKCHITIETXUA989455");

                    b.HasOne("QuanLyCuaHangSach.Models.Sach", "SachidsachNavigation")
                        .WithMany("Chitietxuats")
                        .HasForeignKey("Sachidsach")
                        .HasConstraintName("FKCHITIETXUA898676");

                    b.Navigation("Phieudathangban");

                    b.Navigation("PhieudathangbanidpdhbNavigation");

                    b.Navigation("SachidsachNavigation");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Httt", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Nganhang", "NganhangidnganhangNavigation")
                        .WithMany("Httts")
                        .HasForeignKey("Nganhangidnganhang")
                        .HasConstraintName("FKHTTT886305");

                    b.Navigation("NganhangidnganhangNavigation");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Khachhang", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Nganhang", "NganhangidnganhangNavigation")
                        .WithMany("Khachhangs")
                        .HasForeignKey("Nganhangidnganhang")
                        .HasConstraintName("FKKHACHHANG96359");

                    b.Navigation("NganhangidnganhangNavigation");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Nhacungcap", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Nganhang", "NganhangidnganhangNavigation")
                        .WithMany("Nhacungcaps")
                        .HasForeignKey("Nganhangidnganhang")
                        .HasConstraintName("FKNHACUNGCAP775616");

                    b.Navigation("NganhangidnganhangNavigation");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Noidungthanhtoan", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Phieudathangmua", "PhieudathangmuaidpdhmNavigation")
                        .WithMany("Noidungthanhtoans")
                        .HasForeignKey("Phieudathangmuaidpdhm")
                        .HasConstraintName("FKNOIDUNGTHA22473");

                    b.HasOne("QuanLyCuaHangSach.Models.Phieuthanhtoantienmua", "PhieuthanhtoantienmuaidptttmNavigation")
                        .WithMany("Noidungthanhtoans")
                        .HasForeignKey("Phieuthanhtoantienmuaidptttm")
                        .HasConstraintName("FKNOIDUNGTHA787343");

                    b.Navigation("PhieudathangmuaidpdhmNavigation");

                    b.Navigation("PhieuthanhtoantienmuaidptttmNavigation");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Noidungthutien", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Phieudathangban", "PhieudathangbanidpdhbNavigation")
                        .WithMany("Noidungthutiens")
                        .HasForeignKey("Phieudathangbanidpdhb")
                        .HasConstraintName("FKNOIDUNGTHU806863");

                    b.HasOne("QuanLyCuaHangSach.Models.Phieuthutienban", "PhieuthutienbanidpttbNavigation")
                        .WithMany("Noidungthutiens")
                        .HasForeignKey("Phieuthutienbanidpttb")
                        .HasConstraintName("FKNOIDUNGTHU127596");

                    b.Navigation("PhieudathangbanidpdhbNavigation");

                    b.Navigation("PhieuthutienbanidpttbNavigation");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Phieudathangban", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Donvivanchuyen", "DonvivanchuyeniddvvcNavigation")
                        .WithMany("Phieudathangbans")
                        .HasForeignKey("Donvivanchuyeniddvvc")
                        .HasConstraintName("FKPHIEUDATHA350616");

                    b.HasOne("QuanLyCuaHangSach.Models.Khachhang", "KhachhangidkhachhangNavigation")
                        .WithMany("Phieudathangbans")
                        .HasForeignKey("Khachhangidkhachhang")
                        .HasConstraintName("FKPHIEUDATHA440685");

                    b.HasOne("QuanLyCuaHangSach.Models.Nhanvien", "NhanvienidnhanvienNavigation")
                        .WithMany("Phieudathangbans")
                        .HasForeignKey("Nhanvienidnhanvien")
                        .HasConstraintName("FKPHIEUDATHA497914");

                    b.HasOne("QuanLyCuaHangSach.Models.Trangthai", "TrangthaiidttNavigation")
                        .WithMany("Phieudathangbans")
                        .HasForeignKey("Trangthaiidtt")
                        .HasConstraintName("FKPHIEUDATHA366751");

                    b.Navigation("DonvivanchuyeniddvvcNavigation");

                    b.Navigation("KhachhangidkhachhangNavigation");

                    b.Navigation("NhanvienidnhanvienNavigation");

                    b.Navigation("TrangthaiidttNavigation");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Phieudathangmua", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Donvivanchuyen", "DonvivanchuyeniddvvcNavigation")
                        .WithMany("Phieudathangmuas")
                        .HasForeignKey("Donvivanchuyeniddvvc")
                        .HasConstraintName("FKPHIEUDATHA339438");

                    b.HasOne("QuanLyCuaHangSach.Models.Nhacungcap", "NhacungcapidnccNavigation")
                        .WithMany("Phieudathangmuas")
                        .HasForeignKey("Nhacungcapidncc")
                        .HasConstraintName("FKPHIEUDATHA67436");

                    b.HasOne("QuanLyCuaHangSach.Models.Nhanvien", "NhanvienidnhanvienNavigation")
                        .WithMany("Phieudathangmuas")
                        .HasForeignKey("Nhanvienidnhanvien")
                        .HasConstraintName("FKPHIEUDATHA486736");

                    b.HasOne("QuanLyCuaHangSach.Models.Trangthai", "TrangthaiidttNavigation")
                        .WithMany("Phieudathangmuas")
                        .HasForeignKey("Trangthaiidtt")
                        .HasConstraintName("FKPHIEUDATHA377929");

                    b.Navigation("DonvivanchuyeniddvvcNavigation");

                    b.Navigation("NhacungcapidnccNavigation");

                    b.Navigation("NhanvienidnhanvienNavigation");

                    b.Navigation("TrangthaiidttNavigation");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Phieuthanhtoantienmua", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Httt", "HtttidhtttNavigation")
                        .WithMany("Phieuthanhtoantienmuas")
                        .HasForeignKey("Htttidhttt")
                        .HasConstraintName("FKPHIEUTHANH436959");

                    b.HasOne("QuanLyCuaHangSach.Models.Nhanvien", "NhanvienidnhanvienNavigation")
                        .WithMany("Phieuthanhtoantienmuas")
                        .HasForeignKey("Nhanvienidnhanvien")
                        .HasConstraintName("FKPHIEUTHANH219561");

                    b.Navigation("HtttidhtttNavigation");

                    b.Navigation("NhanvienidnhanvienNavigation");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Phieuthutienban", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Httt", "HtttidhtttNavigation")
                        .WithMany("Phieuthutienbans")
                        .HasForeignKey("Htttidhttt")
                        .HasConstraintName("FKPHIEUTHUTI514256");

                    b.HasOne("QuanLyCuaHangSach.Models.Nhanvien", "NhanvienidnhanvienNavigation")
                        .WithMany("Phieuthutienbans")
                        .HasForeignKey("Nhanvienidnhanvien")
                        .HasConstraintName("FKPHIEUTHUTI142264");

                    b.Navigation("HtttidhtttNavigation");

                    b.Navigation("NhanvienidnhanvienNavigation");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Sach", b =>
                {
                    b.HasOne("QuanLyCuaHangSach.Models.Loaisach", "LoaisachidloaiNavigation")
                        .WithMany("Saches")
                        .HasForeignKey("Loaisachidloai")
                        .HasConstraintName("FKSACH513020");

                    b.HasOne("QuanLyCuaHangSach.Models.Ngonngu", "NgonnguidngonnguNavigation")
                        .WithMany("Saches")
                        .HasForeignKey("Ngonnguidngonngu")
                        .HasConstraintName("FKSACH970053");

                    b.HasOne("QuanLyCuaHangSach.Models.Nhaxuatban", "NhaxuatbanidnxbNavigation")
                        .WithMany("Saches")
                        .HasForeignKey("Nhaxuatbanidnxb")
                        .HasConstraintName("FKSACH492486");

                    b.HasOne("QuanLyCuaHangSach.Models.Tacgia", "TacgiaidtacgiaNavigation")
                        .WithMany("Saches")
                        .HasForeignKey("Tacgiaidtacgia")
                        .HasConstraintName("FKSACH553672");

                    b.Navigation("LoaisachidloaiNavigation");

                    b.Navigation("NgonnguidngonnguNavigation");

                    b.Navigation("NhaxuatbanidnxbNavigation");

                    b.Navigation("TacgiaidtacgiaNavigation");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Donvivanchuyen", b =>
                {
                    b.Navigation("Phieudathangbans");

                    b.Navigation("Phieudathangmuas");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Httt", b =>
                {
                    b.Navigation("Phieuthanhtoantienmuas");

                    b.Navigation("Phieuthutienbans");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Khachhang", b =>
                {
                    b.Navigation("Phieudathangbans");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Loaisach", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Nganhang", b =>
                {
                    b.Navigation("Httts");

                    b.Navigation("Khachhangs");

                    b.Navigation("Nhacungcaps");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Ngonngu", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Nhacungcap", b =>
                {
                    b.Navigation("Phieudathangmuas");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Nhanvien", b =>
                {
                    b.Navigation("Phieudathangbans");

                    b.Navigation("Phieudathangmuas");

                    b.Navigation("Phieuthanhtoantienmuas");

                    b.Navigation("Phieuthutienbans");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Nhaxuatban", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Phieudathangban", b =>
                {
                    b.Navigation("Chitietxuats");

                    b.Navigation("Chitietxuatss");

                    b.Navigation("Noidungthutiens");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Phieudathangmua", b =>
                {
                    b.Navigation("Chitietnhaps");

                    b.Navigation("Noidungthanhtoans");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Phieuthanhtoantienmua", b =>
                {
                    b.Navigation("Noidungthanhtoans");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Phieuthutienban", b =>
                {
                    b.Navigation("Noidungthutiens");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Sach", b =>
                {
                    b.Navigation("Chitietnhaps");

                    b.Navigation("Chitietxuats");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Tacgia", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("QuanLyCuaHangSach.Models.Trangthai", b =>
                {
                    b.Navigation("Phieudathangbans");

                    b.Navigation("Phieudathangmuas");
                });
#pragma warning restore 612, 618
        }
    }
}
